### PR TITLE
Leaderboard-setup-project

### PR DESCRIPTION
**Pull request by elad237**
In this milestone,
 I have set up a JavaScript project for the Leaderboard list app, using webpack and ES6 features, notably modules. 
I have develop the first working version of the app following a wireframe, 
I have used the Leaderboard API using JavaScript async and await and add some styling

### CODE REVIEW

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi @elad237,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) workflow is not correctly used, Kindly make this Pull Request to compare changes from the feature branch to the development(dev) branch. 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# INVALID ❌ ❌ ❌ 

Hi @elad237, 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
 - As the previous code reviewer mentioned, you did not follow the Gitflow approach. Please [read this article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) and make sure you use Gitflow in this project. Also, your branch name is too general, the branch should have the name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). Kindly change the name of your branch to make it professional.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

----
_Invalid Code Review Request does not count into the code reviews limit._

**Review by iambenkis — CHANGES_REQUESTED** [review]
# INVALID   
 Hi @elad237, wave
 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request 
* As the previous code reviewer mentioned, you did not follow the Gitflow approach. Please [read this article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) and make sure you use Gitflow in this project. Also, your branch name is too general, the branch should have the name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). Kindly change the name of your branch to make it professional.

 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
 
Cheers and Happy coding!clapclapclap
 
white_check_mark Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
**_warning Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

 _Invalid Code Review Request does not count into the code reviews limit._

**Comment by TuyishimireEric** [comment]
# INVALID ❌ ❌ ❌
### Hi @elad237, 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
As the previous code reviewer mentioned, you did not follow the Gitflow approach. Please [read this article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) and make sure you use Gitflow in this project. Also, your branch name is too general, the branch should have the name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). Kindly change the name of your branch to make it professional.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


Kindly create  a new PR that follows the Gitflow approach

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

---
_Invalid Code Review Request does not count into the code reviews limit._

**Comment by elad237** [comment]
> # INVALID ❌ ❌ ❌
> ### Hi @elad237, 👋
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request ❌
> As the previous code reviewer mentioned, you did not follow the Gitflow approach. Please [read this article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) and make sure you use Gitflow in this project. Also, your branch name is too general, the branch should have the name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). Kindly change the name of your branch to make it professional. Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Kindly create a new PR that follows the Gitflow approach
> 
> Cheers and Happy coding!👏👏👏
> 
> ✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> ⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
> 
> _Invalid Code Review Request does not count into the code reviews limit._

i dont really understand

**Comment by elad237** [comment]
i am currently working in the feature branch

**Pull request merged**
